server:
  port: 8081
  servlet:
    context-path: /producer
spring:
  artemis:
    host: artemis
    port: 61616
    mode: native
    user: avelon
    password: bluechip
logging:
  level:
   org.apache.activemq.artemis: info
